---
title: 'Pesquisa Tecnológica: Qualitativa e Quantitativa & Estatística Aplicada a
  PI&TT'
author: "Equipe de Professores do Profnit"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
fontsize: 12pt
geometry: a4paper
description: 'Material didático para a disciplina de *Pesquisa Tecnológica: Qualitativa
  e Quantitativa & Estatística Aplicada a PI&TT*.'
---

# Introdução

## Objetivo da proposta

Desenvolver material didático complementar para a disciplina *Pesquisa Tecnológica: Qualitativa e Quantitativa & Estatística Aplicada a PI&TT*

Pressupostos para elaboração do material didático:

-   Material didático consoante às técnicas aplicáveis ao contexto de avaliação de impacto de políticas públicas na área PI & PP ou correlatas (mas não exclusivo. Trata-se apenas de uma base para a elaboração do material).

-   Foco na análise de dados (foco no operacional da pesquisa).

-   Desenvolvimento de tutorais para utilização em ferramentas diversas (Excel, SPSS, R e Python), quando aplicável. O Prof. Tadeu se compromete a elaborar o material em R e Python.

-   Criação de material didático seguindo o modelo da The WIPO Manual on Open Source Patent Analytics (<https://wipo-analytics.github.io/>), além dos slides tradicicionais.

-   Os grupos que elaborarem cada aula/tema serão co-autores dos capítulos do ebook.

## Construção do material didático: ideias gerais

1.  A proposta é criar, em cada aula (capítulo aqui no livro) uma seção inicial com os conceitos fundamentais e os aspectos formais necessários ao entendimento dos conceitos. A ideia não é replicar os livros especializados, mas fazer uma transposição didática com foco na operacionalização para alunos que nunca viram o tema (partiremos desse pressuposto).
2.  Na sequência, apresenta-se exemplos de artigos recentes que os conceitos e técnicas foram empregados, mostrando como construir uma análise empregando os conceitos e técnicas de análise.
3.  Por fim, pode-se construir um tutorial para operacionalização da pesquisa em ferramentas de análise (Excel, SPSS, R, Python e outros). Esta seção poderá ter vários tutoriais para cada tópico em diferentes ferramentas para facilitar a utilização pelos discentes.

### Proposta de programa para organização das aulas/encontros

+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Equipe responsável      | Aulas                                                                                                                                                         |
+=========================+===============================================================================================================================================================+
| Tadeu - Material Pronto | Aula 1                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Nivelamento em linguagem R (Vamos incluir Python também). Material disponível a partir [dessa página](https://tadeugomes.github.io/intro-analise-dados-adm/). |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 2                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Métodos e técnicas de coleta de dados em pesquisa qualitativa.                                                                                                |
|                         |                                                                                                                                                               |
|                         |                                                                                                                                                               |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 3                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Análise e tratamento de informações em pesquisas qualitativas. Métodos de análise qualitativa e análise de conteúdo.                                          |
|                         |                                                                                                                                                               |
|                         |                                                                                                                                                               |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tadeu -Material Pronto  | Aula 4                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Mineração de textos e análise léxica.                                                                                                                         |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Tadeu - Material Pronto | Aula 5                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Análise exploratória e visualização de dados.  Matriz de variância-covariância. Interpretação dos resultados.                                                 |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 6                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Noções de probabilidade.                                                                                                                                      |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 7                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Tipos e técnicas de amostragens.                                                                                                                              |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 8                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Testes de hipótese.                                                                                                                                           |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 9                                                                                                                                                        |
|                         |                                                                                                                                                               |
|                         | Regressão linear simples e múltipla.                                                                                                                          |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 10                                                                                                                                                       |
|                         |                                                                                                                                                               |
|                         | Modelos de classificação: regressão logística.                                                                                                                |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                         | Aula 11                                                                                                                                                       |
|                         |                                                                                                                                                               |
|                         | Análise de variância                                                                                                                                          |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
