---
title: "Pesquisa Tecnológica: Qualitativa e Quantitativa & Estatística Aplicada a PI&TT"
author: "Equipe de Professores do Profnit"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Material didático para a disciplina de *Pesquisa Tecnológica: Qualitativa e Quantitativa & Estatística Aplicada a PI&TT*."
---

# Introdução

## Objetivo da proposta

Desenvolver material didático complementar para a disciplina *Pesquisa Tecnológica: Qualitativa e Quantitativa & Estatística Aplicada a PI&TT*

Pressupostos para elaboração do material didático:

-   Material didático consoante às técnicas aplicáveis ao contexto de avaliação de impacto de políticas públicas na área PI & PP ou correlatas (mas não exclusivo. Trata-se apenas de uma base para a elaboração do material).

-   Foco na análise de dados (foco no operacional da pesquisa).

-   Desenvolvimento de tutorais para utilização em ferramentas diversas (Excel, SPSS, R e Python), quando aplicável.

-   Criação de material didático seguindo o modelo da The WIPO Manual on Open Source Patent Analytics (<https://wipo-analytics.github.io/>), além dos slides tradicicionais.

-   Os grupos que elaborarem cada aula/tema serão co-autores dos capítulos do ebook.

## Construção do material didático: ideias gerais 

1.  A proposta é criar, em cada aula (capítulo aqui no livro) uma seção inicial com os conceitos fundamentais e os aspectos formais necessários ao entendimento dos conceitos. A ideia não é replicar os livros especializados, mas fazer uma transposição didática com foco na operacionalização para alunos que nunca viram o tema (partiremos desse pressuposto).
2.  Na sequência, apresenta-se exemplos de artigos recentes que os conceitos e técnicas foram empregados, mostrando como construir uma análise empregando os conceitos e técnicas de análise.
3.  Por fim, pode-se construir um tutorial para operacionalização da pesquisa em ferramentas de análise (Excel, SPSS, R, Python e outros). Esta seção poderá ter vários tutoriais para cada tópico em diferentes ferramentas para facilitar a utilização pelos discentes.

### Proposta de programa para organização das aulas/encontros

+--------------------+--------------------------------------------------------------------------------------------------------------------+
| Equipe responsável | Aulas                                                                                                              |
+====================+====================================================================================================================+
|                    | Aula 1                                                                                                             |
|                    |                                                                                                                    |
|                    | Métodos e técnicas de coleta de dados em pesquisa qualitativa.                                                     |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 2                                                                                                             |
|                    |                                                                                                                    |
|                    | Análise e tratamento de informações em pesquisa qualitativa. Métodos de análise qualitativa e análise de conteúdo. |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
| Tadeu              | Aula 3                                                                                                             |
|                    |                                                                                                                    |
|                    | Organização dos dados: coleta, limpeza, tratamento e organização. Bases de dados.                                  |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 4                                                                                                             |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    | Noções de probabilidade. Tipos e natureza das variáveis.                                                           |
|                    |                                                                                                                    |
|                    | Inferência causal e contrafactuais em avaliação em políticas públicas.                                             |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
| Tadeu              | Aula 5                                                                                                             |
|                    |                                                                                                                    |
|                    | Análise exploratória dos dados e Visualização.  A matriz de variância-covariância. Interpretação dos resultados.   |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 6                                                                                                             |
|                    |                                                                                                                    |
|                    | Tipos e técnicas de amostragens.                                                                                   |
|                    |                                                                                                                    |
|                    | Seleção aleatória para avaliação de impacto de políticas públicas.                                                 |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 7                                                                                                             |
|                    |                                                                                                                    |
|                    | Testes de hipóteses.                                                                                               |
|                    |                                                                                                                    |
|                    | Pareamento em avaliação de políticas públicas.                                                                     |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 8                                                                                                             |
|                    |                                                                                                                    |
|                    | Regressão linear simples e múltipla. PLS: Mínimos Quadrados Parciais. Interpretação dos resultados.                |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 9                                                                                                             |
|                    |                                                                                                                    |
|                    | Modelos de classificação: regressão logística.                                                                     |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
|                    | (Ou Regressão Descontínua, mais utilizada em avaliação de políticas públicas)                                      |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
|                    | Aula 10 -- Diferença em diferenças em avaliação de políticas públicas                                              |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
| Tadeu              | Aula 11 - Mineração de textos e análise léxica.                                                                    |
|                    |                                                                                                                    |
|                    |                                                                                                                    |
+--------------------+--------------------------------------------------------------------------------------------------------------------+
